[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_move_token = "6ySFsZ7tQ66zmLpuhfri8FhMzFDHNQeGWbGwsAuzJst4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thinhnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
